# -*- coding: utf-8 -*-
"""Project4:Netflix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkzW3Ye_g-E2fRZ7vLyZ8YEuEIJP5baV

# Netflix Content Analysis — Exploratory Data Analysis (EDA)

This project analyzes the Netflix Titles dataset from Kaggle to uncover trends in global content production, genre preferences, release patterns, and platform growth. The goal is to clean the dataset, explore key variables, and derive insights relevant to business and content strategy.

## Project Overview

This analysis answers the following key questions:

1. How many Movies vs TV Shows does Netflix host?
2. Which countries produce the most Netflix content?
3. What are the trends in release years?
4. Which genres/categories are most common?
5. How has Netflix’s catalog grown over time?

The workflow includes:
- Data loading & inspection  
- Data cleaning (dates, genres, countries)  
- Feature engineering  
- Visual exploration  
- Business-focused insights

### Step 1: Import Libraries and Load Dataset

We begin by importing core Python libraries (Pandas and Matplotlib) and loading the Netflix dataset from Google Drive/Colab.
"""

import pandas as pd
import matplotlib.pyplot as plt

"""### Step 2: Initial Data Exploration

We preview the dataset to understand its structure, number of rows/columns, and the types of variables included.

"""

df = pd.read_csv("/content/drive/MyDrive/IDS400/netflix_titles_nov_2019.csv")
df.head()

"""#### Dataset Info
`df.info()` helps identify:
- Column data types  
- Missing values  
- Memory usage  

"""

df.info()

"""### Step 3: Movies vs TV Shows

We compare the number of Movies and TV Shows to understand Netflix’s content strategy and catalog structure.

"""

counts = df['type'].value_counts()

plt.figure(figsize=(6,4))
plt.bar(counts.index, counts.values)
plt.title("Movies vs TV Shows")
plt.xlabel("Type")
plt.ylabel("Count")

plt.show()

"""#### Insights
- Movies significantly outnumber TV Shows.
- This suggests Netflix leans more toward one-time content consumption.
- TV Shows, though fewer, often drive long-term platform engagement.

### Step 4: Country-Wise Content Production

Netflix hosts content from many regions. We split the `country` column and compute which nations contribute the most titles.
"""

country_counts = df['country'].str.split(',', expand= True).stack().str.strip().value_counts()
top10 = country_counts.head(10)

plt.figure(figsize=(10,6))
plt.barh(top10.index, top10.values)
plt.title("Top 10 Countries Producing Netflix Content")
plt.xlabel("Number of Titles")
plt.ylabel("Country")
plt.gca().invert_yaxis()  # biggest at top
plt.show()

"""#### Insights
- The United States produces the largest share of Netflix titles.
- India and the UK also contribute heavily, indicating diversified global production.
- Emerging markets may represent growth opportunities.

### Step 5: Movies vs TV Shows by Country

We compare the counts of Movies and TV Shows for the top 10 countries by total number of titles.
This helps highlight regional content strategies as to which markets produce a large volume of movies vs. TV shows and can reveal opportunities for targeted investments (e.g., expanding TV show production in regions with high movie-heavy catalogs).

Netflix hosts content from many regions. We split the `country` column and `Type` column to compute which nations contribute the most titles.
"""

df_expanded = df.copy()
df_expanded['country_split'] = df_expanded['country'].str.split(',')

df_expanded = df_expanded.explode('country_split')
df_expanded['country_split'] = df_expanded['country_split'].str.strip()

country_type_counts = df_expanded.groupby(['country_split', 'type']).size().unstack(fill_value=0)
top10_countries = country_type_counts.sum(axis=1).sort_values(ascending=False).head(10)

plot_data = country_type_counts.loc[top10_countries.index]

plot_data.plot(kind='bar', figsize=(12,6))
plt.title("Movies vs TV Shows by Country (Top 10)")
plt.xlabel("Country")
plt.ylabel("Count")
plt.xticks(rotation=45, ha='right')
plt.show()

"""#### Insights

- The United States and India contribute the largest number of titles; the US catalog is heavily movie-dominant while India also shows a large movie share.
- Some countries (e.g., Japan, South Korea) have a relatively higher share of TV shows compared to others, suggesting local markets produce/perceive more serialized content.
- For business strategy: investing in TV series in markets that show a stronger TV-show share could increase long-term engagement; conversely, markets dominated by movies may respond better to increased one-off content or film acquisitions.

### Step 6: Release Year Trends

This shows how Netflix’s catalog has evolved over time.
"""

year_counts = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(12,6))
plt.plot(year_counts.index, year_counts.values)
plt.title("Number of Netflix Titles Released Each Year")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.grid(True)
plt.show()

"""#### Insights
- Sharp increase after 2015 aligns with Netflix’s global expansion.
- Recent years show consistent growth in new releases.

### Step 7: Genre Distribution

Genres tell us what type of content Netflix invests in and what audiences consume most.
"""

df_genre = df.copy()
df_genre['genres'] = df_genre['listed_in'].str.split(',')
df_genre = df_genre.explode('genres')
df_genre['genres'] = df_genre['genres'].str.strip()
genre_counts = df_genre['genres'].value_counts()
genre_counts.head(20)
top15 = genre_counts.head(15)

plt.figure(figsize=(12,6))
plt.barh(top15.index, top15.values)
plt.gca().invert_yaxis()
plt.title("Top 15 Genres on Netflix")
plt.xlabel("Number of Titles")
plt.ylabel("Genre")
plt.show()

"""#### Insights
- Dramas, Documentaries, and Comedies dominate.
- Niche categories appear much less frequently.

## Final Summary & Business Insights

#### Key Findings
- Netflix’s catalog is dominated by Movies.
- The US, India, and UK are leading contributors.
- Release-year distribution shows rapid expansion post-2015.
- Drama, Documentary, and Comedy are the top genres.
- Content additions peak between August–November.

#### Business Interpretation
- Netflix focuses on quantity-driven movie uploads.
- Strong global diversification shows international strategy.
- Genre investment aligns with mass audience tastes.
- Seasonal content additions may relate to engagement cycles.

This analysis provides a data-driven view of Netflix’s content strategy and market positioning.
"""